In [2]:
import numpy as np

In [52]:
a = np.array([1,2,3,4,5])

In [53]:
b = np.array([0,9,8,7,6])

In [54]:
c = np.vstack([a, b])

In [55]:
c

array([[1, 2, 3, 4, 5],
       [0, 9, 8, 7, 6]])

In [56]:
z = np.flip(b)


In [57]:
z

array([6, 7, 8, 9, 0])

In [58]:
d = np.hstack([a, z])

In [59]:
d

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [63]:
e = np.reshape(c, (5, 2))

In [61]:
e

array([[1, 2],
       [3, 4],
       [5, 0],
       [9, 8],
       [7, 6]])

In [64]:
c.shape

(2, 5)

In [65]:
e.shape

(5, 2)

In [66]:
f = np.reshape(c, (10, 1))

In [67]:
f

array([[1],
       [2],
       [3],
       [4],
       [5],
       [0],
       [9],
       [8],
       [7],
       [6]])

In [68]:
g = np.reshape(c, (1, 10))

In [69]:
g

array([[1, 2, 3, 4, 5, 0, 9, 8, 7, 6]])

In [3]:
ar1 = np.array([10, 20, 30, 40, 50, 60, 70])

In [7]:
ar1[[2,3,5]]

array([30, 40, 60])