In [357]:
import numpy as np

In [358]:
arr1 = np.array([1,2,3], dtype= 'int8')

In [359]:
arr1

array([1, 2, 3], dtype=int8)

In [360]:
arr1.dtype

dtype('int8')

In [361]:
arr2 = np.array([1.0, 2.0, 3])

In [362]:
arr2.dtype

dtype('float64')

In [363]:
arr2

array([1., 2., 3.])

In [364]:
arr2[:2,]

array([1., 2.])

In [365]:
arr2[1:]

array([2., 3.])

In [366]:
arr3 = np.array([[1,2,3], [4,5,6]])

In [367]:
arr3.shape

(2, 3)

In [368]:
arr3[1]

array([4, 5, 6])

In [369]:
arr3[1, 2]

6

In [370]:
arr3[0:, :2]

array([[1, 2],
       [4, 5]])

In [371]:
arr1

array([1, 2, 3], dtype=int8)

In [372]:
arr1[1:3]

array([2, 3], dtype=int8)

In [373]:
arr2

array([1., 2., 3.])

In [374]:
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [375]:
arr3[0, 1:]

array([2, 3])

In [376]:
arr3[:, 1]

array([2, 5])

In [377]:
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [378]:
arr3[1:, :2] = [9, 8]

In [379]:
arr3.shape

(2, 3)

In [380]:
arr4 = np.array([[[1,2,3,4,5], 
                  [0,9,8,7,6], 
                  [4,5,6,7,8]],
                   
                 [[5,6,7,8,9], 
                  [9,5,7,6,3], 
                  [4,5,6,7,8]]], dtype='int64')

In [381]:
print(arr4.ndim , arr4.shape)

3 (2, 3, 5)


In [382]:
arr4[:, 1, 2] = [7, 8]

In [383]:
arr4

array([[[1, 2, 3, 4, 5],
        [0, 9, 7, 7, 6],
        [4, 5, 6, 7, 8]],

       [[5, 6, 7, 8, 9],
        [9, 5, 8, 6, 3],
        [4, 5, 6, 7, 8]]], dtype=int64)

In [384]:
temp = arr4[0, 0, 1]
arr4[0, 0, 1] = arr4[1, 2, 1]
arr4[1, 2, 1] = temp

In [404]:
arr4

array([[[1, 5, 3, 4, 5],
        [0, 9, 7, 7, 6],
        [4, 5, 6, 7, 8]],

       [[5, 6, 7, 8, 9],
        [9, 5, 8, 6, 3],
        [4, 2, 6, 7, 8]]], dtype=int64)

In [405]:
#arr4[:, 1, 1:4] = [0,0,0]

arr5 = np.ones(arr4.shape, dtype='int32')

In [406]:
arr5 = arr5[:,:,:] * 255 #  arr5 = arr * 255

In [407]:
arr5[:, 1, 1:4] = arr4[:, 1, 1:4]

In [408]:
arr5

array([[[255, 255, 255, 255, 255],
        [255,   9,   7,   7, 255],
        [255, 255, 255, 255, 255]],

       [[255, 255, 255, 255, 255],
        [255,   5,   8,   6, 255],
        [255, 255, 255, 255, 255]]])

In [409]:
print(arr5.shape)

(2, 3, 5)


In [410]:
for i in range(len(arr5[0,0])):
    arr5[:, :, i] = (arr5[:, :, i])-i
print(arr5)
print(arr5.shape)

[[[255 254 253 252 251]
  [255   8   5   4 251]
  [255 254 253 252 251]]

 [[255 254 253 252 251]
  [255   4   6   3 251]
  [255 254 253 252 251]]]
(2, 3, 5)


In [411]:
arr5

array([[[255, 254, 253, 252, 251],
        [255,   8,   5,   4, 251],
        [255, 254, 253, 252, 251]],

       [[255, 254, 253, 252, 251],
        [255,   4,   6,   3, 251],
        [255, 254, 253, 252, 251]]])

In [412]:
arr4

array([[[1, 5, 3, 4, 5],
        [0, 9, 7, 7, 6],
        [4, 5, 6, 7, 8]],

       [[5, 6, 7, 8, 9],
        [9, 5, 8, 6, 3],
        [4, 2, 6, 7, 8]]], dtype=int64)

In [413]:
arr5[:, 1, 1:4] = arr4[:, 1, 1:4]

In [414]:
arr5

array([[[255, 254, 253, 252, 251],
        [255,   9,   7,   7, 251],
        [255, 254, 253, 252, 251]],

       [[255, 254, 253, 252, 251],
        [255,   5,   8,   6, 251],
        [255, 254, 253, 252, 251]]])

In [415]:
for i in range(len(arr5[0, 0])):
    arr5[:, :, i] += i
print(arr5)

[[[255 255 255 255 255]
  [255  10   9  10 255]
  [255 255 255 255 255]]

 [[255 255 255 255 255]
  [255   6  10   9 255]
  [255 255 255 255 255]]]


In [416]:
arr5[:, 1:2, 1:4] = arr4[:, 1:2, 1:4]
arr5

array([[[255, 255, 255, 255, 255],
        [255,   9,   7,   7, 255],
        [255, 255, 255, 255, 255]],

       [[255, 255, 255, 255, 255],
        [255,   5,   8,   6, 255],
        [255, 255, 255, 255, 255]]])