In [1]:
import numpy as np

Linear Algebra

In [2]:
a = np.array([[1,2,3], [4,5,6]])

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
a+5

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [5]:
a-3

array([[-2, -1,  0],
       [ 1,  2,  3]])

In [6]:
a*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [8]:
a//2

array([[0, 1, 1],
       [2, 2, 3]], dtype=int32)

In [9]:
a/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [17]:
z = np.full((3,4), 5)
y = np.full((4,5), 6)

In [18]:
z

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [12]:
y

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [13]:
z*y

ValueError: operands could not be broadcast together with shapes (3,4) (4,5) 

In [14]:
np.matmul(z, y)

array([[120, 120, 120, 120, 120],
       [120, 120, 120, 120, 120],
       [120, 120, 120, 120, 120]])

In [19]:
np.full_like(z, 8)

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [26]:
c = np.identity(8)

In [27]:
c

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [28]:
np.linalg.det(c)

1.0

Statistics

In [29]:
x = np.array([[0,9,8,7], [1,2,3,4]])

In [30]:
x

array([[0, 9, 8, 7],
       [1, 2, 3, 4]])

In [37]:
x.max(axis=1)

array([9, 4])

In [39]:
np.max(x, axis=0)

array([1, 9, 8, 7])

In [40]:
x.min(axis=0)

array([0, 2, 3, 4])

In [41]:
np.min(x, axis=0)

array([0, 2, 3, 4])

In [42]:
sum(x)

array([ 1, 11, 11, 11])

In [43]:
sum(x, axis=0)

TypeError: 'axis' is an invalid keyword argument for sum()

In [44]:
np.sum(x, axis=0)

array([ 1, 11, 11, 11])

In [45]:
np.sum(x)

34